
buildlin-job:
  stage: build
  script:
    - ./bootstrap
    - ./configure --prefix=${PWD}/../openocd_lin --enable-ftdi --enable-ftdi-oscan1 
    - make distclean
    - make clean
    - make -j4
    - make install

buildwin-job:
  stage: build
  script:
    - export OCDLIB_DIR=/home/ocdlib
    - export VER_LIBUSB="1.0.25"
    - export VER_FTD2XX="v2.12.36.4"
    - export LIBUSB1_CFLAGS="-I$OCDLIB_DIR/libusb-$VER_LIBUSB/include/libusb-1.0"
    - export LIBUSB1_LIBS=" -L$OCDLIB_DIR/libusb-$VER_LIBUSB/MinGW64/dll -L$OCDLIB_DIR/libusb-$VER_LIBUSB/MinGW64/static -L$OCDLIB_DIR/libusb-$VER_LIBUSB/MinGW32/dll -L$OCDLIB_DIR/libusb-$VER_LIBUSB/MinGW32/static -lusb-1.0"
    - export libusb_CFLAGS="$LIBUSB1_CFLAGS"
    - export libusb_LIBS="$LIBUSB1_LIBS"
    - ./bootstrap
    - export CFLAGS="$CFLAGS -I$OCDLIB_DIR/libyaml_0_2_2/include -I$OCDLIB_DIR/ftd2xx_$VER_FTD2XX/"
    - export LDFLAGS="$LDFLAGS -L$OCDLIB_DIR/libyaml_0_2_2/bin  -L$OCDLIB_DIR/libyaml_0_2_2/lib -L$OCDLIB_DIR/ftd2xx_$VER_FTD2XX/amd64 -L$OCDLIB_DIR/ftd2xx_$VER_FTD2XX/i386 "
    - ./configure --prefix=${PWD}/../openocd_win --build=x86_64-w64-mingw64 --host=x86_64-w64-mingw32 --enable-ftdi --enable-ftdi-oscan1 
    - make distclean
    - make clean
    - make -j4
    - make install

test-job1:
  stage: test
  script:
    - sleep 1

test-job2:
  stage: test
  script:
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
